# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2d97e524b4f185ac8ad4cedf46f070b856bf9496a0ca20eb03906a5a9f9e46d49228283760a8c6dcc025ad683027e594b420b50323c66fa681636541e3dc8ba

test:
  secret_key_base: 5f3e4911e12a0a77061df9f9e24d4284582f3ff79162ecb5b8ee238ab9d80f7d3389c3e0b59f2d4bcbd9492f7789e46dda2b45315323f7c201ec0d0e5a753f9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
